# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 08:05
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180519_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
