# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reports_allowed_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reports_allowed_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
