# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180510_1642'),
        ('accounts', '0007_profile_reports_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='checks',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
