# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180430_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.IntegerField(default=30),
        ),
    ]
