# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180503_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reports_allowed_daily',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reports_allowed_weekly',
        ),
    ]
