# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180503_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_period',
            field=models.CharField(default=b'daily', max_length=50),
        ),
    ]
