# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_report_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='report_period',
            field=models.CharField(default='daily', max_length=50, null=True),
        ),
    ]
