# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180507_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='report_period',
        ),
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(default='daily', max_length=200),
        ),
    ]
