# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20180517_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Faqs',
        ),
    ]
