# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20180518_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
